### ISSUE TITLE
Spigot 1.8.8 Compability Error

### ISSUE THREAD

**Issue by ardagokcek** [Mirreski/Skript#52]
[17:31:28] [Craft Scheduler Thread - 9/WARN]: Exception in thread "Craft Scheduler Thread - 9" 
[17:31:28] [Craft Scheduler Thread - 9/WARN]: org.apache.commons.lang.UnhandledException: Plugin Skript v2.2-Fixes-V8b generated an exception while executing task 59
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at ch.njol.skript.Skript$4.run(Skript.java:517)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

I got this message in my console. Running server Spigot 1.8.8-R0.1, thanks.

**Comment by FUZIK** [comment]
https://github.com/bensku/Skript

**Comment by synthetic65535** [comment]
I have the same issue on Thermos 1.7.10 build 58 forge 1614.


[07:28:02] [Craft Scheduler Thread - 5/WARN]: Exception in thread "Craft Scheduler Thread - 5" 
[07:28:02] [Craft Scheduler Thread - 5/WARN]: org.apache.commons.lang.UnhandledException: Plugin Skript v2.2-Fixes-V8b generated an exception while executing task 7
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at ch.njol.skript.Skript$4.run(Skript.java:517)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by synthetic65535** [comment]
Looks like it was fixed [here](https://github.com/Mirreski/Skript/commit/0575666c10627670555ad4bb1eae6191d096b3be) but I cannot find a compiled version of V9b...
Only [Early V9b](https://github.com/Mirreski/Skript/issues/38#issuecomment-123526406) without this fix...

**Comment by synthetic65535** [comment]
I fixed this by editing Skript.class via InClassTranslator changing [this URL](https://github.com/Mirreski/Skript/blob/0575666c10627670555ad4bb1eae6191d096b3be/src/main/java/ch/njol/skript/Skript.java#L527) to my local web-server. It is harmless error, I just wanted to have no stacktraces in my latest.log =)

**Comment by ardagokcek** [comment]
You can use Bensku's Skript.

Sent from my iPhone

On 30 Jul 2017, at 11:37, synthetic65535 <notifications@github.com<mailto:notifications@github.com>> wrote:


I fixed this by editing Skript.class via InClassTranslator changing this URL<https://github.com/Mirreski/Skript/blob/0575666c10627670555ad4bb1eae6191d096b3be/src/main/java/ch/njol/skript/Skript.java#L527> to my local we-server. It is harmless error, I just wanted to have no stacktraces in my latest.log =)
