### ISSUE TITLE
Skript server thread :/

### ISSUE THREAD

**Issue by martinbabec1014** [Mirreski/Skript#53]
Hello,
When I restart the server, sometimes the scripts load normally without any problem (4 in total), but sometimes it happens that only one will be loaded and it will be written to the console:
> [14:56:09 INFO]: [Skript] Checking for the latest version of Skript... 
> [14:56:09 INFO]: [Skript] Loading variables... 
> [14:56:09 INFO]: [Skript] Loaded 49 variables in 0.0 seconds 
> [14:56:09 INFO]: [Skript] An internal error occurred while checking for the latest version of Skript. Please refer to the server log for details. 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! [Skript] Severe Error: 
> [14:56:09 ERROR]: #!#! Unexpected error while checking for a new version of Skript 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong. 
> [14:56:09 ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/ 
> [14:56:09 ERROR]: #!#! and check whether this error has already been reported. 
> [14:56:09 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it, 
> [14:56:09 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error. 
> [14:56:09 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well. 
> [14:56:09 ERROR]: #!#! By following this guide fixing the error should be easy and done fast. 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Stack trace: 
> [14:56:09 ERROR]: #!#! javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1] 
Message: Premature end of file. 
> [14:56:09 ERROR]: #!#! at com.sun.org.apache.xerces.internal.impl.XMLStreamReaderImpl.next(XMLStreamReaderImpl.java:596) 
> [14:56:09 ERROR]: #!#! at com.sun.xml.internal.stream.XMLEventReaderImpl.nextEvent(XMLEventReaderImpl.java:83) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.Updater.getChangelogs(Updater.java:286) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.Updater$2.run(Updater.java:210) 
> [14:56:09 ERROR]: #!#! at java.lang.Thread.run(Thread.java:745) 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Version Information: 
> [14:56:09 ERROR]: #!#! Skript: 2.2-Fixes-V8 
> [14:56:09 ERROR]: #!#! Bukkit: 1.8.8-R0.1-SNAPSHOT 
> [14:56:09 ERROR]: #!#! Minecraft: 1.8.8 
> [14:56:09 ERROR]: #!#! Java: 1.8.0_101 (Java HotSpot(TM) 64-Bit Server VM 25.101-b13) 
> [14:56:09 ERROR]: #!#! OS: Linux amd64 3.16.0-0.bpo.4-amd64 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Running CraftBukkit: false 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Current node: replace all "kokoti" in the message with "******" (CMGChat.sk, line 40) 
> [14:56:09 ERROR]: #!#! Current item: null 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Thread: Skript update thread 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! End of Error. 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 INFO]: [Skript] You're currently running a beta version of Skript, and no new stable version is available. Please note that you have to update to newer beta versions manually! 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! [Skript] Severe Error: 
> [14:56:09 ERROR]: #!#! Could not load Jobs.sk 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong. 
> [14:56:09 ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/ 
> [14:56:09 ERROR]: #!#! and check whether this error has already been reported. 
> [14:56:09 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it, 
> [14:56:09 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error. 
> [14:56:09 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well. 
> [14:56:09 ERROR]: #!#! By following this guide fixing the error should be easy and done fast. 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Stack trace: 
> [14:56:09 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for brewerinventory 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:242) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1394) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1115) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1061) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:220) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:175) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:320) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:417) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1136) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1061) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1088) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1088) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1088) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1088) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1127) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1088) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:220) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:175) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.Condition.parse(Condition.java:83) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:729) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.command.Commands.loadCommand(Commands.java:467) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:469) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:245) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:199) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.Skript$2.run(Skript.java:408) 
> [14:56:09 ERROR]: #!#! at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) 
> [14:56:09 ERROR]: #!#! at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) 
> [14:56:09 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) 
> [14:56:09 ERROR]: #!#! at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) 
> [14:56:09 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) 
> [14:56:09 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) 
> [14:56:09 ERROR]: #!#! at java.lang.Thread.run(Thread.java:745) 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Version Information: 
> [14:56:09 ERROR]: #!#! Skript: 2.2-Fixes-V8 
> [14:56:09 ERROR]: #!#! Bukkit: 1.8.8-R0.1-SNAPSHOT 
> [14:56:09 ERROR]: #!#! Minecraft: 1.8.8 
> [14:56:09 ERROR]: #!#! Java: 1.8.0_101 (Java HotSpot(TM) 64-Bit Server VM 25.101-b13) 
> [14:56:09 ERROR]: #!#! OS: Linux amd64 3.16.0-0.bpo.4-amd64 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Running CraftBukkit: false 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Current node: if arg 1 is not set: (Jobs.sk, line 5) 
> [14:56:09 ERROR]: #!#! Current item: null 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Thread: Server thread 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! End of Error. 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! [Skript] Severe Error: 
> [14:56:09 ERROR]: #!#! Could not load RandomTP.sk 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong. 
> [14:56:09 ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/ 
> [14:56:09 ERROR]: #!#! and check whether this error has already been reported. 
> [14:56:09 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it, 
> [14:56:09 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error. 
> [14:56:09 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well. 
> [14:56:09 ERROR]: #!#! By following this guide fixing the error should be easy and done fast. 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Stack trace: 
> [14:56:09 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for brewerinventory 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:242) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1394) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1115) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1061) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:220) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:175) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:320) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:417) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1136) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1088) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:220) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:175) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.Condition.parse(Condition.java:83) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:729) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.TriggerSection.(TriggerSection.java:56) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.Conditional.(Conditional.java:46) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:736) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:510) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:245) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:199) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.Skript$2.run(Skript.java:408) 
> [14:56:09 ERROR]: #!#! at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) 
> [14:56:09 ERROR]: #!#! at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) 
> [14:56:09 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) 
> [14:56:09 ERROR]: #!#! at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) 
> [14:56:09 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) 
> [14:56:09 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) 
> [14:56:09 ERROR]: #!#! at java.lang.Thread.run(Thread.java:745) 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Version Information: 
> [14:56:09 ERROR]: #!#! Skript: 2.2-Fixes-V8 
> [14:56:09 ERROR]: #!#! Bukkit: 1.8.8-R0.1-SNAPSHOT 
> [14:56:09 ERROR]: #!#! Minecraft: 1.8.8 
> [14:56:09 ERROR]: #!#! Java: 1.8.0_101 (Java HotSpot(TM) 64-Bit Server VM 25.101-b13) 
> [14:56:09 ERROR]: #!#! OS: Linux amd64 3.16.0-0.bpo.4-amd64 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Running CraftBukkit: false 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Current node: if line 2 of block is "[RTP]": (RandomTP.sk, line 55) 
> [14:56:09 ERROR]: #!#! Current item: null 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Thread: Server thread 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! End of Error. 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! [Skript] Severe Error: 
> [14:56:09 ERROR]: #!#! Could not load UltraCMGSurvival.sk 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! If you're developing an add-on for Skript this likely means that you have done something wrong. 
> [14:56:09 ERROR]: #!#! If you're a server admin however please go to http://dev.bukkit.org/server-mods/skript/tickets/ 
> [14:56:09 ERROR]: #!#! and check whether this error has already been reported. 
> [14:56:09 ERROR]: #!#! If not please create a new ticket with a meaningful title, copy & paste this whole error into it, 
> [14:56:09 ERROR]: #!#! and describe what you did before it happened and/or what you think caused the error. 
> [14:56:09 ERROR]: #!#! If you think that it's a trigger that's causing the error please post the trigger as well. 
> [14:56:09 ERROR]: #!#! By following this guide fixing the error should be easy and done fast. 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Stack trace: 
> [14:56:09 ERROR]: #!#! ch.njol.skript.SkriptAPIException: No class info found for brewerinventory 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.registrations.Classes.getClassInfo(Classes.java:242) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.getExprInfo(SkriptParser.java:1394) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1115) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse_i(SkriptParser.java:1061) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:220) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parse(SkriptParser.java:175) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parseSingleExpr(SkriptParser.java:320) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.SkriptParser.parseExpression(SkriptParser.java:417) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:668) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.TriggerSection.(TriggerSection.java:56) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.lang.Conditional.(Conditional.java:46) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadItems(ScriptLoader.java:736) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.command.Commands.loadCommand(Commands.java:467) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScript(ScriptLoader.java:469) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:245) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.ScriptLoader.loadScripts(ScriptLoader.java:199) 
> [14:56:09 ERROR]: #!#! at ch.njol.skript.Skript$2.run(Skript.java:408) 
> [14:56:09 ERROR]: #!#! at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) 
> [14:56:09 ERROR]: #!#! at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) 
> [14:56:09 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) 
> [14:56:09 ERROR]: #!#! at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) 
> [14:56:09 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) 
> [14:56:09 ERROR]: #!#! at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) 
> [14:56:09 ERROR]: #!#! at java.lang.Thread.run(Thread.java:745) 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Version Information: 
> [14:56:09 ERROR]: #!#! Skript: 2.2-Fixes-V8 
> [14:56:09 ERROR]: #!#! Bukkit: 1.8.8-R0.1-SNAPSHOT 
> [14:56:09 ERROR]: #!#! Minecraft: 1.8.8 
> [14:56:09 ERROR]: #!#! Java: 1.8.0_101 (Java HotSpot(TM) 64-Bit Server VM 25.101-b13) 
> [14:56:09 ERROR]: #!#! OS: Linux amd64 3.16.0-0.bpo.4-amd64 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Running CraftBukkit: false 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Current node: loop 300 times: (UltraCMGSurvival.sk, line 6) 
> [14:56:09 ERROR]: #!#! Current item: null 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! Thread: Server thread 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 ERROR]: #!#! End of Error. 
> [14:56:09 ERROR]: #!#! 
> [14:56:09 INFO]: [Skript] All scripts loaded without errors. 
> [14:56:09 INFO]: [Skript] Loaded 1 script with a total of 1 trigger and 0 commands in 0.17 seconds 
> [14:56:09 INFO]: [Skript] Finished loading. 
Please help, my server is based on scripts :/ :(

**Comment by LamboCreeper** [comment]
I recommend posting the issue over at [skUnity Forums](http://forums.skunity.com).

**Comment by martinbabec1014** [comment]
Here dont work authentication emails  for me so I can not write to the forum :/

**Comment by martinbabec1014** [comment]
My problem has been resolved, i download Skript v2.2 (not fixed or anything) and works great

**Comment by martinbabec1014** [comment]
I wrote here that it was solved .... But it was a mistake .... :( :( Version 2.2 wrote me basically the same as the previous .... it was that I server maybe 10x restart and always It was written to me that all 4 scripts have been successfully loaded ... but on the 11th attempt it wrote to me again what I did before:

https://pastebin.com/QtHb8V7F
